name: My First Workflow
on: [push, pull_request]
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: job-1-step-1
        run: echo "Triggered by push-1 ..."
        
      - name: job-2-step-2
        run: echo "Triggered by push-2 ..."
  job-2:
     runs-on: ubuntu-latest
     steps:
      - name: job-2-step-1
        uses: actions/setup-go@v2 
        with:
          go-version: '1.15.1'
        
